InterfaceMvc/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Repositorio;
using Dominio;
using System.Web.Helpers;
using InterfaceMvc.Code;
using InterfaceMvc.Ninject;

namespace InterfaceMvc.Controllers
{
    [Authorize]
    public class UsuarioController : Controller
    {
        private IRepositorioUsuario repUsuario;
        private IRepositorioRegistro repRegistro;
        public UsuarioController(IRepositorioUsuario repUsuario, IRepositorioRegistro repRegistro)
        {
            this.repUsuario = repUsuario;
            this.repRegistro = repRegistro;
        }
        //
        // GET: /Usuario/
        //private UnitOfWork db = new UnitOfWork();
        public ActionResult List()
        {
           
                var user = repUsuario.ObterPorId((User as InterfaceMvc.Code.Sercutiry.CustomPrincipal).Id);
                return View(repUsuario.Obter(u => u.IdFamilia == user.IdFamilia));
            
        }


        public ActionResult Info()
        {

            return View(repUsuario.ObterPorId((User as InterfaceMvc.Code.Sercutiry.CustomPrincipal).Id));
            
          
        }

        public ActionResult Create()
        {
            return View();
        }

        [Transaction]
        public ActionResult Create(FormCollection collection)
        {
            
                Usuario usario = new Usuario();
                usario.Nome = collection["Nome"];
                repUsuario.Inserir(usario);

                return View("Index", repUsuario.ObterTodos());
            
        }


        public ActionResult Edit(int id = 0)
        {

            return View(repUsuario.ObterPorId(id));
            
        }


        [HttpPost, ActionName("Edit")]
        public ActionResult EditConfirm(FormCollection collection, int id = 0)
        {

               var item = repUsuario.ObterPorId(id);
                item.Nome = collection["Nome"];
                repUsuario.Atualizar(item);

                return View("List", repUsuario.ObterTodos());
            
        }


        public ActionResult Delete(int id = 0)
        {

            return View(repUsuario.ObterPorId(id));
            
        }

        [HttpPost, ActionName("Delete")]
        [Transaction]
        public ActionResult DeleteCofirmed(int id)
        {

            repUsuario.Excluir(repUsuario.ObterPorId(id));

            return View("List", repUsuario.ObterTodos());
            
        }

        public ActionResult Convite()
        {
           
                var convite = new Registro();
                return PartialView("Convite", convite);
            
        }

        [Transaction]
        public ActionResult SendInvite(Registro convite)
        {
            

                var user = (User as InterfaceMvc.Code.Sercutiry.CustomPrincipal);


                if (repUsuario.ExisteUsuario(convite.Convidado.Email))
                {
                    ModelState.AddModelError("Email", "Email já existe para um cadastro ativo.");
                    return PartialView("Convite", convite);
                }


                convite.Convidado.Familia = repUsuario.ObterPorId(user.Id).Familia;
                convite.DtEnviado = DateTime.Now;
                convite.Chave = Guid.NewGuid();
                convite.Ativo = true;
                convite.Tipo = eTipoRegistro.Convite;
                convite = repRegistro.Inserir(convite);
                
                var url = Request.Url;
                var baseurl = url.GetLeftPart(UriPartial.Authority);
                EMail mailer = new EMail();
                baseurl = baseurl + Url.Action("Aceite", "Home", new { verifycode = convite.Chave });
                mailer.SendMail(eMailType.Convidar, convite.Convidado.Email, new string[] { user.Familia }, new string[] { user.FirstName, user.Familia, baseurl });
                return RedirectToAction("List", new { id = user.Id });
            }
        

    }
}

InterfaceMvc/Views/Usuario/Convite.cshtml
@model Dominio.Registro
@using (Html.BeginForm("SendInvite", "Usuario", FormMethod.Post))
{
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
    </button>
    <h3 id="myModalLabel1">
        @Resources.OrcamentoResource.lblConvidar @Resources.OrcamentoResource.lblParticipante</h3>
</div>
<div class="modal-body">
    <div class="editor-label">
        <label>@Resources.OrcamentoResource.lblNome</label>
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Convidado.Nome)
        @Html.ValidationMessageFor(model => model.Convidado.Nome)
    </div>
    <div class="editor-label">
        <label>Email</label>
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Convidado.Email)
        @Html.ValidationMessageFor(model => model.Convidado.Email)
    </div>
</div>
<div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">
        @Resources.OrcamentoResource.lblCancelar</button>
    <button type="submit" name="SendInvite" class="btn yellow">
        @Resources.OrcamentoResource.lblEnviar</button>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InterfaceMvc/Views/Usuario/Create.cshtml
@model Dominio.Usuario

@{
    ViewBag.Title = Resources.OrcamentoResource.lblCriar + " " + Resources.OrcamentoResource.lblUsuario;
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>@Resources.OrcamentoResource.lblUsuario</legend>

        <div class="editor-label">
            <label>@Resources.OrcamentoResource.lblNome</label>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Nome)
            @Html.ValidationMessageFor(model => model.Nome)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink(@Resources.OrcamentoResource.lblVoltar, "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InterfaceMvc/Views/Usuario/Delete.cshtml
@model Dominio.Usuario

@{
    ViewBag.Title = @Resources.OrcamentoResource.lblDeletar + " " + @Resources.OrcamentoResource.lblUsuario;
}

<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN SAMPLE FORM PORTLET-->
        <div class="portlet box blue">
            <div class="portlet-title">
                <h4>
                    <i class="icon-reorder"></i>@Resources.OrcamentoResource.lblDeletar @Resources.OrcamentoResource.lblUsuario</h4>
            </div>
            <div class="portlet-body form">
                <!-- BEGIN FORM-->
                <form action="@Url.Action("Delete")" class="horizontal-form" method="post">
                @Html.HiddenFor(model => model.IdUsuario)
                <div class="control-group">
                   <label class="control-label">@Resources.OrcamentoResource.lblNome</label>
                    <div class="controls">
                        @Html.TextBoxFor(model => model.Nome, new { @readonly = "readonly", @class = "span6 m-wrap" })
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Email</label>
                    <div class="controls">
                        @Html.TextBoxFor(model => model.Email, new { @readonly = "readonly", @class = "span6 m-wrap" })
                    </div>
                </div>
                <div class="form-actions">
                    <input type="submit" class="btn blue" value="@Resources.OrcamentoResource.lblDeletar" />
                    @Html.ActionLink(Resources.OrcamentoResource.lblCancelar, "List", "Usuario", null, new { @class = "btn" })
                </div>
                </form>
                <!-- END FORM-->
            </div>
        </div>
        <!-- END SAMPLE FORM PORTLET-->
    </div>
</div>
}

InterfaceMvc/Views/Usuario/Edit.cshtml
@model Dominio.Usuario
@{
    ViewBag.Title = @Resources.OrcamentoResource.lblEditar + " " + @Resources.OrcamentoResource.lblUsuario;
}
<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN SAMPLE FORM PORTLET-->
        <div class="portlet box blue">
            <div class="portlet-title">
                <h4>
                    <i class="icon-reorder"></i>@Resources.OrcamentoResource.lblEditar @Resources.OrcamentoResource.lblUsuario</h4>
            </div>
            <div class="portlet-body form">
                <!-- BEGIN FORM-->
                <form action="@Url.Action("Save")" class="horizontal-form" method="post">
                @Html.HiddenFor(model => model.IdUsuario)
                <div class="control-group">
                    <label class="control-label">@Resources.OrcamentoResource.lblNome</label>
                    <div class="controls">
                        @Html.TextBoxFor(model => model.Nome, new { @readonly = "readonly", @class = "span6 m-wrap" })
                        @Html.ValidationMessageFor(model => model.Nome)
                    </div>
                </div>
                <div class="control-group">
                    @Html.LabelFor(model => model.Nome, new { @class = "control-label" })
                    <div class="controls">
                        @Html.TextBoxFor(model => model.Nome, new { @class = "span6 m-wrap" })
                        @Html.ValidationMessageFor(model => model.Nome)
                    </div>
                </div>
                <div class="form-actions">
                    <input type="submit" class="btn blue" value="@Resources.OrcamentoResource.lblSalvar" />
                    @Html.ActionLink(Resources.OrcamentoResource.lblCancelar, "List", "Usuario", null, new { @class = "btn" })
                </div>
                </form>
                <!-- END FORM-->
            </div>
        </div>
        <!-- END SAMPLE FORM PORTLET-->
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InterfaceMvc/Views/Usuario/Info.cshtml
@model Dominio.Usuario
@{
    ViewBag.Title = @Resources.OrcamentoResource.lblDetalheUsuario;
}
<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN SAMPLE FORM PORTLET-->
        <div class="portlet box blue">
            <div class="portlet-title">
                <h4>
                    <i class="icon-reorder"></i>@Resources.OrcamentoResource.lblDetalheUsuario</h4>
            </div>
            <div class="portlet-body form">
                <!-- BEGIN FORM-->
                <form class="horizontal-form">
                <div class="control-group">
                    <label class="control-label">@Resources.OrcamentoResource.lblNome</label>
                    <div class="controls">
                        @Html.TextBoxFor(model => model.Nome, new { @readonly = "readonly", @class = "span6 m-wrap" })
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">
                        Email</label>
                    <div class="controls">
                        @Html.TextBoxFor(model => model.Email, new { @readonly = "readonly", @class = "span6 m-wrap" })
                    </div>
                </div>
                <div class="form-actions">
                    @Html.ActionLink(Resources.OrcamentoResource.lblVoltar, "Index", "Orcamento", null, new { @class = "btn" })
                </div>
                </form>
                <!-- END FORM-->
            </div>
        </div>
        <!-- END SAMPLE FORM PORTLET-->
    </div>
</div>

InterfaceMvc/Views/Usuario/List.cshtml
@model IEnumerable<Dominio.Usuario>
@{
    ViewBag.Title = @Resources.OrcamentoResource.lblListaParticipante;
    var user = (User as InterfaceMvc.Code.Sercutiry.CustomPrincipal);
}
<!-- BEGIN PAGE CONTENT-->
<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet box blue">
            <div class="portlet-title">
                <h4>
                    <i class="icon-edit"></i>@Resources.OrcamentoResource.lblListaParticipante</h4>
            </div>
            <div class="portlet-body">
                <div class="clearfix">
                    @if (@user.IsAdmin)
                    {
                        <div class="btn-group">
                            <a href="#dialogModal" role="button" class="btn green" data-toggle="modal">@Resources.OrcamentoResource.lblConvidar
                                <i class="icon-envelope"></i></a>
                        </div>
                        <div id="dialogModal" class="modal hide fade in" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1"
                            aria-hidden="false" style="display: none;">
                            @Html.Partial("Convite", new Dominio.Registro())
                        </div>
                    }
                </div>
                <div id="sample_editable_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
                    @{
                                
                        var grid = new WebGrid(source: Model,
                       ajaxUpdateContainerId: "gridUsuario");

                                    
                    }
                    @grid.GetHtml(mode: WebGridPagerModes.All, tableStyle: "table table-striped table-bordered table-advance table-hover",
                                                            fillEmptyRows: false,
                                                            columns: grid.Columns(
                                                            grid.Column("Nome", Resources.OrcamentoResource.lblNome),
                                grid.Column("Email", "Email"), grid.Column(" ", format: (item) =>
                                {

                                    var links = new HtmlString(string.Format("<a href='{0}' class='btn mini red'><i class='icon-edit'></i> {1}</a>", Url.Action("Edit", "Usuario", new { id = item.IdUsuario }), Resources.OrcamentoResource.lblEditar)
                                                                        + string.Format("<a href='{0}' class='btn mini red'><i class='icon-trash'></i> {1}</a>", Url.Action("Delete", "Usuario", new { id = item.IdUsuario }), Resources.OrcamentoResource.lblDeletar));
                                    return user.IsAdmin ? links : Html.Raw("");
                                }

                                                                                  )))
                </div>
                
            </div>
           
        </div>
        <!-- END EXAMPLE TABLE PORTLET-->
         <div class="form-actions">
                    @Html.ActionLink(Resources.OrcamentoResource.lblVoltar, "Index", "Orcamento", null, new { @class = "btn blue", style="float:right" })
                </div>
    </div>
</div>