InterfaceMvc/Models/ExceptionError.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace InterfaceMvc.Models
{
    public class ExceptionError
    {
        public string Message { get; set; }
        public string Error { get; set; }
        public int StatusCode { get; set; }
    }
}

InterfaceMvc/Models/GenericModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace InterfaceMvc.Models
{
    public class GenericModel
    {
        public DateTime Date { get; set; }
    }
}

InterfaceMvc/Models/LoginModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace InterfaceMvc.Models
{
    public class LoginModel
    {
        public string Nome { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor, informe sua senha")]
        [StringLength(50, ErrorMessage = "O {0} deve ter pelo menos {2} caracteres.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        public string Senha { get; set; }

        [Display(Name = "Usuário (Email Address)")]        
        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor, informe seu usuário.")]
        [RegularExpression(".+@.+\\..+", ErrorMessage = "Por favor, informe um email válido!")]
        public string Email { get; set; }

        [Display(Name = "Usuário (Email Address)")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor, informe o nome do seu orçamento.")]
        public string Familia { get; set; }

        [Required(ErrorMessage = "Por favor, repita sua senha.")]
        [StringLength(50, ErrorMessage = "O {0} deve ter pelo menos {2} caracteres.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Confirme sua Senha")]
        [Compare("Senha", ErrorMessage = "Senhas informadas não são iguais.")]
        public string ConfirmPassword { get; set; }

        public Dominio.eTipoRegistro Tipo
        {
            get;
            set;
        }
    }
}

InterfaceMvc/Models/MessageModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace InterfaceMvc.Models
{
    public class MessageModel
    {
        public string UrlRedirect { get; set; }
        public string Message { get; set; }
        public string Title { get; set; }
        public TypeMessage Tipo {get; set;}
    }

    public enum TypeMessage 
    {
        ConfirmRedirect,
        ErroMessage
    }
}

InterfaceMvc/Models/RegisterExternalLoginModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace InterfaceMvc.Models
{
    public class RegisterExternalLoginModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        public string ExternalLoginData { get; set; }

        [Display(Name = "Full name")]
        public string FullName { get; set; }

        [Display(Name = "Personal page link")]
        public string Link { get; set; }


        [Display(Name = "Usuário (Email Address)")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor, informe o nome do seu orçamento.")]
        public string Familia { get; set; }

        public bool? Verified { get; set; }
    }
}

InterfaceMvc/Models/RelatorioModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace InterfaceMvc.Models
{
    public class RelatorioModel
    {
        public List<ResultMonth> Months { get; set; } 
    }

    public class ResultMonth
    {
        public string Data { get; set; }        
        public Dominio.ePeriodo Periodo {get; set;}
        public decimal TotalReceita { get; set; }
        public decimal TotalDespesa { get; set; }
    }

    public class Month
    {
        public string Now { get; set; }
    }
}

InterfaceMvc/Controllers/DespesaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Repositorio;
using Dominio;
using InterfaceMvc.Ninject;
namespace InterfaceMvc.Controllers
{
    [Authorize]
    public class DespesaController : Controller
    {
        //
        // GET: /Despesa/

        private IRepositorioDespesa _repDespesa;
        private IRepositorioUsuario _repUsuario;
        private IRepositorioExtrato _repExtrato;
        public DespesaController(IRepositorioDespesa repDespesa, IRepositorioUsuario repUsuario, IRepositorioExtrato repExtrato)
        {
            _repDespesa = repDespesa;
            _repUsuario = repUsuario;
            _repExtrato = repExtrato;
        }

        public ActionResult Create()
        {

            var user = (User as InterfaceMvc.Code.Sercutiry.CustomPrincipal);
            ViewBag.ListPeriodo = EnumHelper.SelectListFor<ePeriodo>();
            ViewBag.ListTipo = EnumHelper.SelectListFor<eTipo>();
            ViewBag.ListCategoria = EnumHelper.SelectListFor<eCategoria>();

            ViewBag.ListUsuario = new SelectList(_repUsuario.ObterTodos(), "IdUsuario", "Nome", user.Id);
            return View();

        }

        [HttpPost]
        [Transaction]
        public ActionResult Create(Despesa despesa, FormCollection collection)
        {

            var user = (User as InterfaceMvc.Code.Sercutiry.CustomPrincipal);
            if (user.IsAdmin)
            {
                despesa.Usuario = _repUsuario.ObterPorId(Convert.ToInt32(collection["Usuario"]));
            }
            else despesa.Usuario = _repUsuario.ObterPorId(user.Id);
            DateTime apartir = despesa.Data;
            bool repetir = collection["Repetir"] == "on";
            int nrovezes = 1;

            if (repetir)
                nrovezes = Convert.ToInt32(collection["NroVezes"]);

            for (int i = 0; i < nrovezes; i++)
            {
                Despesa item = (Despesa)despesa.Clone();
                item.Data = item.Data.AddMonths(i);
                if (repetir)
                {
                    item.NroParcela = i + 1;
                    item.NroParcelaHaPagar = nrovezes;
                }
                var extrato = _repExtrato.Obter(x => x.Data.Year == item.Data.Year && x.Data.Month == item.Data.Month);

                if (extrato == null)
                {
                    extrato = new Extrato();
                    extrato.Data = item.Data;
                    item.Extrato = _repExtrato.Inserir(extrato);
                }
                _repDespesa.Inserir(item);
            }



            return RedirectToAction("Index", "Orcamento", new { Data = apartir });

        }


        public ActionResult Delete(int id)
        {

            var despesa = _repDespesa.ObterPorId(id);
            return View(despesa);

        }

        [HttpPost]
        [Transaction]
        public ActionResult Delete(FormCollection colletion, int id = 0)
        {
            var despesa = _repDespesa.ObterPorId(id);
            _repDespesa.Excluir(despesa);
            return RedirectToAction("Index", "Orcamento", new { Data = despesa.Data });

        }


        public ActionResult Edit(int id)
        {

            var despesa = _repDespesa.ObterPorId(id);
            ViewBag.ListPeriodo = EnumHelper.SelectListFor(despesa.Periodo);
            ViewBag.ListTipo = EnumHelper.SelectListFor(despesa.Tipo);
            ViewBag.ListCategoria = EnumHelper.SelectListFor(despesa.Categoria);
            return View(despesa);

        }

        [HttpPost]
        [Transaction]
        public ActionResult Save(Despesa despesa, FormCollection colletion, int id = 0)
        {

            var item = _repDespesa.ObterPorId(despesa.IdDespesa);
            var extrato = _repExtrato.Obter(x => x.Data.Year == item.Data.Year && x.Data.Month == item.Data.Month);

            if (extrato == null)
            {
                extrato = new Extrato();
                extrato.Data = item.Data;
                item.Extrato = _repExtrato.Inserir(extrato);
            }

            item.Periodo = despesa.Periodo;
            item.Valor = despesa.Valor;
            item.Pago = despesa.Pago;
            item.Tipo = despesa.Tipo;
            item.Categoria = despesa.Categoria;
            item.Data = despesa.Data;
            item.Descricao = despesa.Descricao;
            _repDespesa.Atualizar(item);

            return RedirectToAction("Index", "Orcamento", new { Data = despesa.Data });




        }
    }
}

InterfaceMvc/Controllers/ReceitaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Repositorio;
using Dominio;
using InterfaceMvc.Ninject;

namespace InterfaceMvc.Controllers
{
    [Authorize]
    public class ReceitaController : Controller
    {
        private IRepositorioReceita _repReceita;
        private IRepositorioUsuario _repUsuario;
        private IRepositorioExtrato _repExtrato;
        public ReceitaController(IRepositorioReceita repReceita, IRepositorioUsuario repUsuario, IRepositorioExtrato repExtrato)
        {
            _repReceita = repReceita;
            _repUsuario = repUsuario;
            _repExtrato = repExtrato;
        }


        //
        // GET: /Receita/

        // private UnitOfWork db = new UnitOfWork();

        public ActionResult Create()
        {

            var user = (User as InterfaceMvc.Code.Sercutiry.CustomPrincipal);
            ViewBag.ListPeriodo = EnumHelper.SelectListFor<ePeriodo>();
            ViewBag.ListTipo = EnumHelper.SelectListFor<eTipo>();
            ViewBag.ListUsuario = new SelectList(_repUsuario.ObterTodos().ToList(), "IdUsuario", "Nome", user.Id);

            return View();

        }

        [HttpPost]
        [Transaction]
        public ActionResult Create(Receita receita, FormCollection collection)
        {

            var user = (User as InterfaceMvc.Code.Sercutiry.CustomPrincipal);
            if (user.IsAdmin)
            {
                receita.Usuario = _repUsuario.Obter(u => u.IdUsuario == Convert.ToInt32(collection["Usuario"]));
            }
            else receita.Usuario = _repUsuario.Obter(u => u.IdUsuario == user.Id);
            bool repetir = collection["Repetir"] == "on";
            int nrovezes = 1;

            if (repetir)
            {
                nrovezes = Convert.ToInt32(collection["NroVezes"]);
            }

            for (int i = 0; i < nrovezes; i++)
            {
                Receita item = (Receita)receita.Clone();
                item.Data = item.Data.AddMonths(i);
                var extrato = _repExtrato.Obter(x => x.Data.Year == item.Data.Year && x.Data.Month == item.Data.Month);

                if (extrato == null)
                {
                    extrato = new Extrato();
                    extrato.Data = item.Data;
                    item.Extrato = _repExtrato.Inserir(extrato);
                }
                _repReceita.Inserir(item);
            }

            

            return RedirectToAction("Index", "Orcamento", new { Data = receita.Data });

        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var receita = _repReceita.ObterPorId(id);
            return View(receita);
        }

        [HttpPost]
        [Transaction]      
        public ActionResult Delete(FormCollection colletion, int id = 0)
        {
           
                var item = _repReceita.ObterPorId(id);
                _repReceita.Excluir(item);                
                return RedirectToAction("Index", "Orcamento", new { Data = item.Data });
           
        }


        public ActionResult Edit(int id)
        {
            
                var receita = _repReceita.ObterPorId(id);                
                ViewBag.ListPeriodo = EnumHelper.SelectListFor(receita.Periodo);
                ViewBag.ListTipo = EnumHelper.SelectListFor(receita.Tipo);
                return View(receita);
            
        }

        [HttpPost]
        [Transaction]  
        public ActionResult Save(Receita receita, FormCollection colletion)
        {
            
                var item =  _repReceita.ObterPorId(receita.IdReceita);

                var extrato = _repExtrato.Obter(x => x.Data.Year == item.Data.Year && x.Data.Month == item.Data.Month);

                if(extrato == null)
                {
                    extrato = new Extrato();
                    extrato.Data = receita.Data;
                    extrato = _repExtrato.Inserir(extrato);                   

                }
                receita.Extrato = extrato;

                item.Valor = receita.Valor;
                item.Periodo = receita.Periodo;
                item.Data = receita.Data;
                item.Descricao = receita.Descricao;
                item.Tipo = receita.Tipo;
                _repReceita.Atualizar(item);

                
                return RedirectToAction("Index", "Orcamento", new { Data = item.Data });
            

        }
    }
}

InterfaceMvc/Views/Shared/SiteLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="description" content="Criar orçamento familiar que pode ser compartilhado entre os membros da família." />
    <meta name="keywords" content="Orçamento Familiar, Orçamento, Orçamento Quinzenal, Quinzena, Orçamento Compartilhado, Compartilhar Orçamento" />
    <meta name="author" content="Double Silva" />
    <meta name="revisit-after" content="15 days" />
    <meta name="robots" content="index,follow" />
    <meta name="distribution" content="global" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/metronic")
    @Scripts.Render("~/bundles/chart")
    @Styles.Render("~/Content/themes/metronic/bootstrap/css/All.css")
    @Styles.Render("~/Content/themes/metronic/css/All.css")
    @Styles.Render("~/Content/themes/metronic/font-awesome/css/All.css")
    @RenderSection("PageScripts", false)
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="fixed-top">
    <!-- BEGIN HEADER -->
    @Html.Partial("_Menu")
    <!-- END HEADER -->
    <!-- BEGIN CONTAINER -->
    <div class="page-container row-fluid">
        <!-- BEGIN PAGE -->
        <div class="page-content">
            <!-- BEGIN PAGE CONTAINER-->
            <div class="container-fluid">
                <div class="page-container row-fluid">
                    <!-- BEGIN PAGE -->
                    <div class="page-content">
                        <div class="container-fluid">
                            <!-- BEGIN PAGE HEADER-->
                            <div class="row-fluid">
                                <div class="span12">
                                    <!-- BEGIN PAGE TITLE & BREADCRUMB-->
                                    <h3 class="page-title">
                                        @{
                                            var nFamilia = (User as InterfaceMvc.Code.Sercutiry.CustomPrincipal).Familia;
                                        }
                                        @Resources.OrcamentoResource.lblOrcamento @nFamilia
                                    </h3>
                                    <!-- END PAGE TITLE & BREADCRUMB-->
                                </div>
                            </div>
                            @RenderBody()
                            <!-- END PAGE CONTENT-->
                        </div>
                        <!-- END PAGE CONTAINER-->
                    </div>
                    <!-- BEGIN PAGE -->
                </div>
                <!-- END CONTAINER -->
            </div>
            @Html.Partial("_Loading");
            <!-- END PAGE CONTAINER-->
            @RenderSection("scripts", required: false)
        </div>
        <!-- END PAGE -->
    </div>
    <!-- END CONTAINER -->
    <!-- BEGIN FOOTER -->
    <div class="footer">
        @Html.Raw(Resources.OrcamentoResource.InfoCoyRight)        
        <div class="span pull-right">
            <span class="go-top"><i class="icon-angle-up"></i></span>
        </div>
    </div>
   
    <!-- END FOOTER -->
</body>
<!-- END BODY -->
</html>
 <script type="text/javascript">

        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
  m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-33048976-1', 'doublesilva.com');
        ga('send', 'pageview');


    </script>

InterfaceMvc/Views/Shared/_Date.cshtml
@model InterfaceMvc.Models.GenericModel
<link href="@Url.Content("~/Content/themes/base/jquery.ui.all.css")" rel="stylesheet" type="text/css" />

<script type="text/javascript">
    $(function () {
        var day = '@Model.Date.Day';
        var month = '@Model.Date.Month';
        var year = '@Model.Date.Year';
        var currentDate = new Date(year, month - 1, day);
        $('.onlyMonthYear').datepicker({
            changeMonth: true,
            changeYear: true,
            showButtonPanel: true,
            dateFormat: 'MM-yy',
            defaultDate: currentDate,
            onClose: function (dateText, inst) {
                var month = $("#ui-datepicker-div .ui-datepicker-month :selected").val();
                var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
                currentDate = new Date(year, month, 1);
                $(this).datepicker('setDate', currentDate);
                $(this).datepicker({ defaultDate: currentDate });
            }
        });
        $('.onlyMonthYear').datepicker('setDate', currentDate);

        $('.add-on').click(function () {
            var visible = $('#ui-datepicker-div').is(':visible');
            $('.onlyMonthYear').datepicker(visible ? 'hide' : 'show');
        });

        jQuery.validator.methods["date"] = function (value, element) {
            var date = $('.onlyMonthYear').datepicker('getDate');
            var result = this.optional(element) || !/Invalid|NaN/.test(date.toString());            
            return result;
        }

    });

    
</script>
<style type="text/css">
    .ui-datepicker-calendar
    {
        display: none;
    }
</style>

InterfaceMvc/Views/Shared/_Grids.cshtml
@model Dominio.Extrato
@{
    decimal amount = 0;
   
        amount = Model.Receitas.Sum(r => r.Valor) - Model.Despesas.Sum(d => d.Pago.HasValue ? d.Pago.Value : d.Valor);

    
    var user = (User as InterfaceMvc.Code.Sercutiry.CustomPrincipal);                    
}
<div class="row-fluid" style="width: 30%; margin-left: 31%;">
    <div class="responsive span3" data-tablet="span6  fix-offset" data-desktop="span3"
        style="margin-left: 40%;">
        @{
            if (amount > 0)
            {    
            @:<div class="dashboard-stat blue">
            }
            else if (amount < 0)
            {
            @:<div class="dashboard-stat red">
            }
            else
            {
            @:<div class="dashboard-stat green">
            }
        }
        <div class="visual" style="color: white;height: 90px;"> <i class="icon-calendar"></i>
        <div id="dtControle" style="text-transform: capitalize; font-size: 150%">@Model.Data.ToString("MMMM/yyyy")</div>
        </div> <div class="details"> <div class="number" style="font-size: 200%;"> @amount.ToString("C2")</div>
        <div class="desc"> @Resources.OrcamentoResource.lblSaldoAtual</div> </div> </div>
        </div> </div>
        <div class="portlet-body">
            <div class="row-fluid">
                <div class="span3">
                    <div class="pricing-table2">
                        <h3>
                            @Resources.OrcamentoResource.lblReceita</h3>
                        <div class="rate">
                            <div class="price">
                                <div class="amount ">
                                    @{
                                        var receitaTotal = 0M;
                                        var grid = new WebGrid(source: Model.Receitas,
                                       ajaxUpdateContainerId: "gridReceita");
                                        receitaTotal = Model.Receitas.Sum(r => r.Valor);
                            
                                    }
                                    @receitaTotal.ToString("c")
                                </div>
                            </div>
                            <a href="@Url.Action("Create", "Receita")" class="btn">@Resources.OrcamentoResource.lblAdicionar
                                <i class="m-icon-swapright"></i></a>
                        </div>
                        @grid.GetHtml(mode: WebGridPagerModes.All, tableStyle: "table table-striped table-bordered table-advance table-hover",
                                                            fillEmptyRows: false,
                                                            columns: grid.Columns(
                                                            grid.Column("Descricao", @Resources.OrcamentoResource.lblDescricao),
                                                            grid.Column("Usuario.Nome", @Resources.OrcamentoResource.lblUsuario),
                                                            grid.Column("Periodo", @Resources.OrcamentoResource.lblPeriodo, style: "description"),
                                                            grid.Column("Valor", @Resources.OrcamentoResource.lblValor, format: (item) => string.Format("{0:C}", item.Valor)),
                                                                     grid.Column(" ", format: item =>
                                                                         {
                                                                             if (@user.IsAdmin || item.IdUsuario == @user.Id)
                                                                             {
                                                                                 return new HtmlString(string.Format("<a href='{0}' class='btn mini red'><i class='icon-edit'></i> {1}</a>", Url.Action("Edit", "Receita", new { id = item.IdReceita }), @Resources.OrcamentoResource.lblEditar)
                                                                               + string.Format("<a href='{0}' class='btn mini red'><i class='icon-trash'></i> {1}</a>", Url.Action("Delete", "Receita", new { id = item.IdReceita }), @Resources.OrcamentoResource.lblDeletar));
                                                                             }
                                                                             else return string.Empty;
                                                                         }
                                                                         )),
                          htmlAttributes: new { @id = "gridReceita" })
                    </div>
                </div>
                <div class="spance10 visible-phone">
                </div>
                <div class="span3">
                    <div class="pricing-table2">
                        <h3>
                            @Resources.OrcamentoResource.lblDespesa</h3>
                        <div class="rate">
                            <div class="price">
                                <div class="amount ">
                                    @{
                                        var despesaTotal = 0M;
                                        var grid2 = new WebGrid(source: Model.Despesas,
                                       ajaxUpdateContainerId: "gridDespesa");
                                        despesaTotal = Model.Despesas.Sum(r => r.Pago.HasValue ? r.Pago.Value : r.Valor);                            
                                    }
                                    @despesaTotal.ToString("c")
                                </div>
                            </div>
                            <a href="@Url.Action("Create", "Despesa")" class="btn">@Resources.OrcamentoResource.lblAdicionar
                                <i class="m-icon-swapright"></i></a>
                        </div>
                        @grid2.GetHtml(mode: WebGridPagerModes.All, tableStyle: "table table-striped table-bordered table-advance table-hover",
                                                            fillEmptyRows: false,
                                                            columns: grid.Columns(
                                                                     grid2.Column("Descricao", @Resources.OrcamentoResource.lblDescricao),
                                                                     grid2.Column("Usuario.Nome", @Resources.OrcamentoResource.lblUsuario),
                                                                     grid2.Column("Periodo", @Resources.OrcamentoResource.lblPeriodo, style: "description"),
                                                                     grid2.Column("Valor", @Resources.OrcamentoResource.lblValPrevisto, format: (item) =>
                                                                     {
                                                                         return string.Format("{0:C} {1}", item.Valor, item.NroParcela > 0 && item.Tipo != Dominio.eTipo.Mensal ? string.Format(@Resources.OrcamentoResource.lblFormatParcels, item.NroParcela, item.NroParcelaHaPagar) : string.Empty);
                                                                     }),
                                                                     grid2.Column(@Resources.OrcamentoResource.lblValPago, format: (item) =>
                                                                     {
                                                                         if (item.Pago != null)
                                                                             return string.Format("{0:C}", item.Pago);
                                                                         else
                                                                         {
                                                                             if (@user.IsAdmin || item.IdUsuario == @user.Id)
                                                                             {
                                                                                 return new HtmlString(string.Format("<a href='#dialogModal' data-toggle='modal' onclick='javascript:ModelPagar({0});' class='btn mini yellow'>" + @Resources.OrcamentoResource.lblPagar + "</a>", item.IdDespesa));
                                                                             }
                                                                             else return string.Empty;
                                                                         }

                                                                     }),
                                                                     grid2.Column(" ", format: item =>
                                                                         {
                                                                             if (@user.IsAdmin || item.IdUsuario == @user.Id)
                                                                             {
                                                                                 return new HtmlString(
                                                                       string.Format("<a href='{0}' class='btn mini red'><i class='icon-edit'></i> {1}</a>", Url.Action("Edit", "Despesa", new { id = item.IdDespesa }), @Resources.OrcamentoResource.lblEditar)
                                                                       + string.Format("<a href='{0}' class='btn mini red'><i class='icon-trash'></i> {1}</a>", Url.Action("Delete", "Despesa", new { id = item.IdDespesa }), @Resources.OrcamentoResource.lblDeletar));
                                                                             }
                                                                             else
                                                                             {
                                                                                 return string.Empty;
                                                                             }
                                                                         })
                                                                    ), htmlAttributes: new { @id = "gridDespesa" })
                    </div>
                </div>
            </div>
        </div>
        <div id="dialogModal" class="modal hide fade in" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1"
            aria-hidden="false" style="display: none;">
        </div>
        <script type="text/javascript">

            function ModelPagar(id) {
                var url = '@Url.Action("Pagar")';
                $.ajax({
                    type: "GET",
                    url: url,
                    cache: false,
                    dataType: "html",
                    data: { iddespesa: id },
                    success: function (data) {
                        $('#dialogModal').html(data);
                    },
                    error: function (data) {
                        alert(data.responseText); // use any display logic here
                    }
                });
            }

        </script>

InterfaceMvc/Views/Shared/_Loading.cshtml
@{
    ViewBag.Title = "_Loading";
}
<style type="text/css">
    #loading
    {
        display:none;
        position:fixed;
        left:0;
        top:0;
        width:100%;
        height:100%;
        background:rgba(255,255,255,0.8);
        z-index:1000;
    }
  
    #loadingcont
    {
        display:table;
        position:fixed;
        left:0;
        top:0;
        width:100%;
        height:100%;
    }
  
    #loadingspinr
    {
        display: table-cell;
        vertical-align:middle;
        width: 100%;
        text-align: center;
        font-size:larger;
        padding-top:80px;
    }
</style>

<div id="loading">
    <div id="loadingcont">
        <p id="loadingspinr">
            @Resources.OrcamentoResource.lblLoading
        </p>
    </div>
</div>


<script type="text/javascript">
    $(function () {
        $(".btn:not('.yellow')").click(function () {
            $("#loading").fadeIn();
        });
    });
</script>